all:
	echo "Pass"

install:
	curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	ln -s $(PWD) ~/.config/nvim
	# Note: Install HIE, Pylint!
