# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@ansible/ansible-language-server-1.2.1" = {
      name = "_at_ansible_slash_ansible-language-server";
      packageName = "@ansible/ansible-language-server";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ansible/ansible-language-server/-/ansible-language-server-1.2.1.tgz";
        sha512 = "Lb8BE8xOxxP5JaatEcnz5UprDhG2tMI4RR95bbj9NHW0C1Vv3EWtfX1yzVA7wk+DxScvAxwPioBAN7NeMrJoUQ==";
      };
    };
    "@flatten-js/interval-tree-1.1.1" = {
      name = "_at_flatten-js_slash_interval-tree";
      packageName = "@flatten-js/interval-tree";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@flatten-js/interval-tree/-/interval-tree-1.1.1.tgz";
        sha512 = "IsD8MPvzlbrUZnqychSEPM0dX6DXFG6ObFVbJs8asb5cwUOCek+Qi10W/mK7N9aqKkNpOSSzEIkrhHOiOXZlXw==";
      };
    };
    "antsibull-docs-1.0.0" = {
      name = "antsibull-docs";
      packageName = "antsibull-docs";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/antsibull-docs/-/antsibull-docs-1.0.0.tgz";
        sha512 = "OqrXCQkKeqTTuFBmQc9RJnXPcjUtRnMq0rfmT3zlp6UHJWTwq1SLffwOEw1I5jC7FNLMoabUjPb8wxCNB3RaZw==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-2.0.1" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.1.tgz";
        sha512 = "XnAIvQ8eM+kC6aULx6wuQiwVsnzsi9d3WxzV3FpWTGA19F621kwdbsAcFKXgKUHZWsy+mY6iL1sHTxWEFCytDA==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha512 = "OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==";
      };
    };
    "glob-9.3.5" = {
      name = "glob";
      packageName = "glob";
      version = "9.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-9.3.5.tgz";
        sha512 = "e1LleDykUz2Iu+MTYdkSsuWX8lvAjAcs0Xef0lNIu0S2wOAzuTxCJtcd9S3cijlwYF18EsU3rzb8jPVobxDh9Q==";
      };
    };
    "ini-4.1.1" = {
      name = "ini";
      packageName = "ini";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-4.1.1.tgz";
        sha512 = "QQnnxNyfvmHFIsj7gkPcYymR8Jdw/o7mp5ZFihxn6h8Ci6fh3Dx4E1gPjpQEpIuPo9XVNY/ZUwh4BPMjGyL01g==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lru-cache-10.0.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "10.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-10.0.1.tgz";
        sha512 = "IJ4uwUTi2qCccrioU6g9g/5rvvVl13bsdczUUcqbciD9iLr095yj8DQKdObriEvuNSx325N1rV1O0sJFszx75g==";
      };
    };
    "minimatch-8.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "8.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-8.0.4.tgz";
        sha512 = "W0Wvr9HyFXZRGIDgCicunpQ299OKXs9RgZfaukz4qAW/pJhcpUfupc9c+OObPOFueNy8VSrZgEmDtk6Kh4WzDA==";
      };
    };
    "minipass-4.2.8" = {
      name = "minipass";
      packageName = "minipass";
      version = "4.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass/-/minipass-4.2.8.tgz";
        sha512 = "fNzuVyifolSLFL4NzpF+wEF4qrgqaaKX0haXPQEdQ7NKAN+WecoKMHV09YcuL/DHxrUsYQOK3MiuDf7Ip2OXfQ==";
      };
    };
    "minipass-7.0.4" = {
      name = "minipass";
      packageName = "minipass";
      version = "7.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass/-/minipass-7.0.4.tgz";
        sha512 = "jYofLM5Dam9279rdkWzqHozUo4ybjdZmCsDHePy5V/PbBcVMiSZR97gmAy45aqi8CK1lG2ECd356FU86avfwUQ==";
      };
    };
    "path-scurry-1.10.1" = {
      name = "path-scurry";
      packageName = "path-scurry";
      version = "1.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-scurry/-/path-scurry-1.10.1.tgz";
        sha512 = "MkhCqzzBEpPvxxQ71Md0b1Kk51W01lrYvlMzSUaIzNsODdd7mqhiimSZlr+VegAz5Z6Vzt9Xg2ttE//XBhH3EQ==";
      };
    };
    "uuid-9.0.1" = {
      name = "uuid";
      packageName = "uuid";
      version = "9.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-9.0.1.tgz";
        sha512 = "b+1eJOlsR9K8HJpow9Ok3fiWOWSIcIzXodvv0rQjVoOVNpWMpxf1wZNpt4y9h10odCNrqnYp1OBzRktckBe3sA==";
      };
    };
    "vscode-jsonrpc-8.1.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.1.0.tgz";
        sha512 = "6TDy/abTQk+zDGYazgbIPc+4JoXdwC8NHU9Pbn4UJP1fehUyZmM4RHp5IthX7A6L5KS30PRui+j+tbbMMMafdw==";
      };
    };
    "vscode-languageserver-8.1.0" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-8.1.0.tgz";
        sha512 = "eUt8f1z2N2IEUDBsKaNapkz7jl5QpskN2Y0G01T/ItMxBxw1fJwvtySGB9QMecatne8jFIWJGWI61dWjyTLQsw==";
      };
    };
    "vscode-languageserver-protocol-3.17.3" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.3.tgz";
        sha512 = "924/h0AqsMtA5yK22GgMtCYiMdCOtWTSGgUOkgEDX+wk2b0x4sAfLiO4NxBxqbiVtz7K7/1/RgVrVI0NClZwqA==";
      };
    };
    "vscode-languageserver-textdocument-1.0.11" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.11.tgz";
        sha512 = "X+8T3GoiwTVlJbicx/sIAF+yuJAqz8VvwJyoMVhwEMoEKE/fkDmrqUgDMyBECcM2A2frVZIUj5HI/ErRXCfOeA==";
      };
    };
    "vscode-languageserver-types-3.17.3" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.3.tgz";
        sha512 = "SYU4z1dL0PyIMd4Vj8YOqFvHu7Hz/enbWtpfnVbJHU4Nd1YNYx8u0ennumc6h48GQNeOLxmwySmnADouT/AuZA==";
      };
    };
    "vscode-uri-3.0.8" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.0.8.tgz";
        sha512 = "AyFQ0EVmsOZOlAnxoFOGOq1SQDWAB7C6aqMGS23svWAllfOaxbuFvcT8D1i8z3Gyn8fraVeZNNmN6e9bxxXkKw==";
      };
    };
    "yaml-2.3.4" = {
      name = "yaml";
      packageName = "yaml";
      version = "2.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-2.3.4.tgz";
        sha512 = "8aAvwVUSHpfEqTQ4w/KMlf3HcRdt50E5ODIQJBw1fQ5RL34xabzxtUlzTXVqc4rkZsPbvrXKWnABCD7kWSmocA==";
      };
    };
  };
in
{
  "@yaegassy/coc-ansible" = nodeEnv.buildNodePackage {
    name = "_at_yaegassy_slash_coc-ansible";
    packageName = "@yaegassy/coc-ansible";
    version = "0.14.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/@yaegassy/coc-ansible/-/coc-ansible-0.14.2.tgz";
      sha512 = "bnBrMxJUlTuk2NWlM8LeX9at+9wBReVnnJSMBMQZuGHOfLmdUDWOPnkLAe7P0mVmLRjVJu/cJa6D+5/w9FiKzQ==";
    };
    dependencies = [
      sources."@ansible/ansible-language-server-1.2.1"
      sources."@flatten-js/interval-tree-1.1.1"
      sources."antsibull-docs-1.0.0"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-2.0.1"
      sources."fs.realpath-1.0.0"
      sources."glob-9.3.5"
      sources."ini-4.1.1"
      sources."lodash-4.17.21"
      sources."lru-cache-10.0.1"
      sources."minimatch-8.0.4"
      sources."minipass-4.2.8"
      (sources."path-scurry-1.10.1" // {
        dependencies = [
          sources."minipass-7.0.4"
        ];
      })
      sources."uuid-9.0.1"
      sources."vscode-jsonrpc-8.1.0"
      sources."vscode-languageserver-8.1.0"
      sources."vscode-languageserver-protocol-3.17.3"
      sources."vscode-languageserver-textdocument-1.0.11"
      sources."vscode-languageserver-types-3.17.3"
      sources."vscode-uri-3.0.8"
      sources."yaml-2.3.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "ansible-language-server extension for coc.nvim";
      homepage = "https://github.com/yaegassy/coc-ansible#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  coc-jedi = nodeEnv.buildNodePackage {
    name = "coc-jedi";
    packageName = "coc-jedi";
    version = "0.36.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/coc-jedi/-/coc-jedi-0.36.1.tgz";
      sha512 = "63PZIDWsymqilCzHsu2ZpWqlsWg+AuG5rgNvEOPTxweo8YLqbNsTyKoLpX5neuXdSnBkyh2QT1r/WgipXn2AAw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "coc.nvim wrapper for the jedi-language-server for Python";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
